apiVersion: v1
kind: Pod
metadata:
  name: sec-context
spec:
  securityContext:
      runAsUser: 1000
      runAsGroup: 3000
  containers:
  - name: sec-context
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
